credentials:
  system:
    domainCredentials:
      - domain: {}
        credentials:
          - basicSSHUserPrivateKey:
              id: "bitbucket_ssh_key"
              scope: GLOBAL
              username: "bitbucket_ssh_key"
              privateKeySource:
                directEntry:
                  privateKey: |-
                    <SSH_PRIVATE_KEY_CONTENT>
  folder: {}
  providerImpl: {}
  user: {}